import type { Metadata } from 'next'
import { Kumbh_Sans } from 'next/font/google'

import './globals.css'

const kumbhSans = Kumbh_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-kumbh-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.variable} antialiased`}>{children}</body>
    </html>
  )
}
